# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Skorubrew
email: skorulis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
twitter_username: skorulis
github_username:  skorulis
timezone: Australia/Sydney

# Build settings
markdown: kramdown
